### ISSUE TITLE
Re-sizing fails if new chunk_size and cache size are not in certain ratios

### ISSUE THREAD

**Issue by thomvet** [SciML/PreallocationTools.jl#3]
First of all, thank you for generating this nice package and also for the resizing added to it in v0.1.1. It removes the requirement to care about chunk sizes, but keeps the performance at maximum. So, that's good.

However, the re-sizing results in a resizing error if the new chunk size required is not equal to one. MWE below (inspired by the readme example):

```
randmat = rand(10, 2)
sto = similar(randmat)
stod = dualcache(sto)

function claytonsample!(sto, τ, α; randmat=randmat)
    sto = get_tmp(sto, τ)
    sto .= randmat
    τ == 0 && return sto

    n = size(sto, 1)
    for i in 1:n
        v = sto[i, 2]
        u = sto[i, 1]
        sto[i, 1] = (1 - u^(-τ) + u^(-τ)*v^(-(τ/(1 + τ))))^(-1/τ)*α
        sto[i, 2] = (1 - u^(-τ) + u^(-τ)*v^(-(τ/(1 + τ))))^(-1/τ)
    end
    return sto
end

#taking the derivative of claytonsample! with respect to τ only
df1 = ForwardDiff.derivative(τ -> claytonsample!(stod, τ, 0.0), 0.3)

#calculating the jacobian of claytonsample! with respect to τ and α
df2 = ForwardDiff.jacobian(x -> claytonsample!(stod, x[1], x[2]), [0.3, 0.3])
```

Leads to:

```
ERROR: ArgumentError: cannot reinterpret an `ForwardDiff.Dual{nothing, Float64, 10}` array to `ForwardDiff.Dual{ForwardDiff.Tag{var"#36#37", Float64}, Float64, 2}` whose first dimension has size `10`.
The resulting array would have non-integral first dimension.
```

The issue is that each `ForwardDiff.Dual{nothing, Float64, 10}` is 88 bytes in size (8 bytes for a Float64 representing the value part and 10 x 8 bytes for the perturbations). The code then tries to reinterpret this into an array containing elements that are 24 bytes each (1 x 8 for the value, 2 x 8 for the perturbations). Since rem(88,24) != 0, the above error results. 

I have an idea for a fix of this issue and hope that I can propose a PR soon and get it reviewed for suitability.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/PreallocationTools.jl/pull/4
