### ISSUE TITLE
Add non-DiffCache method for get_tmp?

### ISSUE THREAD

**Issue by taylormcd** [SciML/PreallocationTools.jl#41]
It seems like whenever this code is used in the wild, there's generally some sort of check to see if `get_tmp` can be called. Here's a few examples from the SciML ecosystem:

https://github.com/SciML/OrdinaryDiffEq.jl/blob/54fe504bdf56654b3ecab996da0bcae461898114/src/initialize_dae.jl#L310-L311

https://github.com/SciML/OrdinaryDiffEq.jl/blob/7167a8d26b6eced8f26479066c23ec0acd636bcb/src/nlsolve/utils.jl#L93-L99

https://github.com/SciML/SciMLSensitivity.jl/blob/8fe8212197631d5a5897a9b653583bf97ebcf69f/src/derivative_wrappers.jl#L241-L243

In fact, in my short search I didn't find any scenarios in the SciML ecosystem where `get_tmp` was called without being wrapped in this manner. 

While it isn't hard to wrap calls to `get_tmp` this way, I feel like it would be cleaner if this check was done inside PreallocationTools rather than outside it.  The only change would be defining the method:

```julia
get_tmp(dc, u) = dc
```

Is there a good reason for keeping the current behavior?

**Comment by thomvet** [comment]
I think this would be a good change! Do you want to PR it or should I?

**Comment by ChrisRackauckas** [comment]
Seems reasonable to me.
