### ISSUE TITLE
More descriptive "About" for repository

### ISSUE THREAD

**Issue by DanielVandH** [SciML/PreallocationTools.jl#56]
The current description of the repository is "Speed at all costs" which isn't so descriptive I feel. This also sticks out when going through the other repositories in the SciML org since all others have a complete description. Maybe something like 

"Tools for building non-allocating pre-cached functions in Julia"

(or whatever else, that's just from the README) could be good to have.

**Comment by ChrisRackauckas** [comment]
Done
