### ISSUE TITLE
Extending DualCache for Array of matrices 

### ISSUE THREAD

**Issue by andreichalapco** [SciML/PreallocationTools.jl#74]
Hi,
I was using the package and when trying to use the diffcache in the following example
```julia
C = DiffCache([rand(3, 3) for _ in 1:3]) 
```
it throws me an error that I can zero the type Matrix{Float64} although this should be possible ... 
The only workaround I found is using something in the lines of DiffCache(rand(3,3, 3)).
Is there a good idea to extend the library to have this functionality to include arrays of matrices?

**Comment by ChrisRackauckas** [comment]
FixedSizeDiffCache and LazyBufferCache should work fine for this. Did you try those?

**Comment by andreichalapco** [comment]
Thx! Will look into that!
